#!C:\Users\pathos\Downloads\PL-v0.0.6\python-3.10.11-embed\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
